---
# This playbook provisions the ovirt topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: "{{ default_roles_path }}/common" }

- name:  "Provisioning ovirt resources"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'ovirt' }

- name: "Gather resources to the RunDB"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: "{{ default_roles_path }}/gather_resources"}

- name: "inventory generation role"
  hosts: localhost
  gather_facts: True
  roles:
    - role: "{{ default_roles_path }}/inventory_gen"
      when:
        - state == 'present'
        - layout_file is defined or layout is defined
