---
- name: "provision beaker systems"
  bkr_server:
    whiteboard: "{{ res.whiteboard | default('Provisioned with linchpin') }}"
    recipesets: "{{ res.recipesets }}"
    state: present
    job_group: "{{ res.job_group | default('') }}"
  with_items: "{{ res_defs['resource_definitions'] }}"
  loop_control:
    loop_var: res
  register: bkr

#- name: debug bkr.results['ids']
#  debug:
#    var: result['ids']
#  with_items: "{{ bkr.results }}"
#  loop_control:
#    loop_var: result
#  when: state == 'present'

- name: "fetch beaker details"
  bkr_info:
    ids: "{{ result['ids'] }}"
  with_items: "{{ bkr.results }}"
  loop_control:
    loop_var: result
  when: state == 'present'
  register: _topology_outputs_beaker_server

- name: "append beaker outputs"
  set_fact:
    topology_outputs_beaker_server: "{{ topology_outputs_beaker_server + bkr_item.hosts }}"
  with_items: "{{ _topology_outputs_beaker_server.results }}"
  loop_control:
    loop_var: bkr_item
  when: state == 'present'

